### ISSUE TITLE
BUG: lint rule E602 concatinate results from previous erros

### ISSUE THREAD

**Issue by vutkin** [lean-delivery/ansible-lint-rules#11]
##### SUMMARY

lint rule E602 concatinate results from previous erros
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-lint
##### ANSIBLE VERSION

```
Ansible 2.5.x
```

##### CONFIGURATION

Ansible 2.5.x
##### OS / ENVIRONMENT

gitlab-runner
##### STEPS TO REPRODUCE
ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
##### EXPECTED RESULTS

E602 Line too long  (110 characters)
##### ACTUAL RESULTS

E602 Line too long (101 characters) (101 characters) (128 characters) (140 characters) (115 characters) (102 characters) (104 characters) (110 characters)

```

```

**Comment by tgadiev** [comment]
@vutkin is it still in place?

**Comment by tgadiev** [comment]
This bug is not relevant anymore.
